### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by sazanca** [sazanca/chat-space#12]
# IPアドレス
54.249.130.125

**Comment by mo1015** [comment]
守屋さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○サイドバー上部の見た目が見本と異なる**
<img width="1440" alt="修正2" src="https://user-images.githubusercontent.com/62644781/81466267-4cdbf300-920b-11ea-8557-2238ddc09ece.png">

**○投稿のユーザー名、日付の見た目が見本と異なる**
（リロードすると解消する）
<img width="1440" alt="修正" src="https://user-images.githubusercontent.com/62644781/81466248-156d4680-920b-11ea-89fe-73ddd249cc70.png">



修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
